# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Server-Side Swift
email: max.desiatov@gmail.com
description: A newsletter with the best links related to server-side Swift and cross-platform developer tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.serverswift.tech" # the base hostname & protocol for your site
twitter_username: ServerSideSwift
github_username:  explicitcall
exclude: [firebase.json, params.json]

# Build settings
markdown: kramdown
