# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Server-side Swift
email: max.desiatov@gmail.com
description: A newsletter with the best links related to server-side Swift, Swift on Linux and Swift build system.
baseurl: "/ServerSideSwift" # the subpath of your site, e.g. /blog
url: "https://explicitcall.github.io" # the base hostname & protocol for your site
twitter_username: ServerSideSwift
github_username:  explicitcall

# Build settings
markdown: kramdown
